### ISSUE TITLE
'DOMDocument'

### ISSUE THREAD

**Issue by fraba** [AKSW/OntoWiki#434]
Hello,

I completed the installation and successfully connected it to Virtuoso. Still, I get this error when I access the page:

`Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/html/ontowiki/OntoWiki-1.0.0/vendor/zendframework/zendframework1/library/Zend/Feed.php:200 Stack trace: #0 /var/www/html/ontowiki/OntoWiki-1.0.0/vendor/zendframework/zendframework1/library/Zend/Feed.php(182): Zend_Feed::importString('<?xml version="...') #1 /var/www/html/ontowiki/OntoWiki-1.0.0/application/controllers/IndexController.php(151): Zend_Feed::import('http://blog.aks...') #2 /var/www/html/ontowiki/OntoWiki-1.0.0/application/controllers/IndexController.php(74): IndexController->getNews() #3 /var/www/html/ontowiki/OntoWiki-1.0.0/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): IndexController->newsAction() #4 /var/www/html/ontowiki/OntoWiki-1.0.0/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('newsAction') #5 /var/www/html/ontowiki/OntoWiki-1.0.0/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Disp in /var/www/html/ontowiki/OntoWiki-1.0.0/vendor/zendframework/zendframework1/library/Zend/Feed.php on line 200`

`php7.0-xml` is already installed.

**Comment by fraba** [comment]
It seems that `php-mbstring` is also required.
